### ISSUE TITLE
Linux-内存性能篇 

### ISSUE THREAD

**Issue by 0XFF-96** [Alex1996a/golang-snippet#4]
### 参考

- 计算机系统基础： https://www.icourse163.org/learn/NJU-1001964032?tid=1450227475#/learn/content

- 虚拟内存知识系列： https://www.youtube.com/watch?v=qlH4-oHnBb8&t=1s 
- 虚拟内存知识： https://www.youtube.com/watch?v=qcBIvnQt0Bw&list=PLiwt1iVUib9s2Uo5BeYmwkDFUh70fJPxX&index=1 

- proc 文件系统: https://www.cnblogs.com/cute/archive/2011/04/20/2022280.html 

- udacity 的文件系统：https://www.udacity.com/course/gt-refresher-advanced-os--ud098

- 什么是文件系统：https://www.youtube.com/watch?v=KN8YgJnShPM

- 内存回收的水位： https://blog.csdn.net/jasonchen_gbd/article/details/79462014

**Comment by Alex1996a** [comment]
### 参考资料

目前我配合使用《Operating System Concepts》这本书学习此专栏，也是一个不错的选择。此书中的第四部分“Memory Management”对今天这部分内容有较为详细的描述，感兴趣的同学可以去看一下。另外对于TOP命令中输出的内存情况解释，可以认真看一下man手册的内容。如果你动手能力比较强，可以看https://blog.holbertonschool.com/hack-the-virtual-memory-malloc-the-heap-the-program-break/这篇博客，手把手教你使用程序（C语言）来实际地去搞清楚虚拟内存分布

**Comment by 0XFF-96** [comment]
- [x]  基础篇：Linux内存是怎么工作的？
- [x]  基础篇：怎么理解内存中的Buffer和Cache？
- [x]  案例篇：如何利用系统缓存优化程序的运行效率？
- [x]  案例篇：内存泄漏了，我该如何定位和处理？
- [x]  案例篇：为什么系统的Swap变高了（上）
- [x]  案例篇：为什么系统的Swap变高了？（下）
- [x]  套路篇：如何“快准狠”找到系统内存的问题？
- [x]  答疑（三）：文件系统与磁盘的区别是什么？




### 参考
- 换算关系：https://blog.csdn.net/u014737138/article/details/50909218?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.nonecase&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.nonecase 

-

**Comment by 0XFF-96** [comment]
### 内存的作用
内存主要用来存储系统和应用程序的指令、数据、缓存

### 什么是内存映射？
将虚拟内存地址映射到物理内存地址， 通过 CPU 的内存管理单元，MMU 。

### MMU 如何管理内存？
- 管理的单位
- 页表
- 机制：多级页表/大页 （HugePage) 

### 虚拟内存空间分布
- 只读段、数据段、堆、文件映射段、栈


### 内存分配与回收
- 回收缓存 LRU 算法
- OOM（Out of memory ) 杀死进程 

### 利用 free 查看内存相关知识

**Comment by 0XFF-96** [comment]
### 怎么理解内存中的 Buffer 和 Cache ?

### Buffer 和 Cache 的区别？
- 字面理解：缓冲区和缓存
-  man free 解析
- Buffers 是内核缓冲区的内存， 对应与 `/proc/meminfo` 的值
- Cache 是内核页缓存和 Slab 用到的是内存，对应与 `/proc/meminfo` 中的 Cached 与SReclaimable 之和。 

### proc 文件系统
- proc 文件系统是许多工具的数据来源。 

```
Buffers %lu
    Relatively temporary storage for raw disk blocks that shouldn't get tremendously large (20MB or so).

Cached %lu
   In-memory cache for files read from the disk (the page cache).  Doesn't include SwapCached.
...
SReclaimable %lu (since Linux 2.6.19)
    Part of Slab, that might be reclaimed, such as caches.
    
SUnreclaim %lu (since Linux 2.6.19)
    Part of Slab, that cannot be reclaimed on memory pressure.
```

- Buffers 是对原始磁盘块对临时存储，用来缓存磁盘的数据
- Cached 是从磁盘读取文件的页存储，用来缓存从文件读取的数据
- SReclaimable 是 Slab 的一部分。


- Buffer 和 Cache 分别缓存的是对磁盘和文件系统对读写数据。 

### 实验1

**Comment by 0XFF-96** [comment]
### 如何利用系统缓存优化程序的运行效率？

### 缓存命中率
- 命中率越高，表示使用缓存带来的收益越高，应用程序的性能也就越好。 

### 工具按照

- cachestat 提供了整个操作系统缓存的读写命中情况
- cachetop 提供了每个进程的缓存命中情况
- pcstat : 查看文件在内存中的缓存大小已经缓存比例


### 实验一
### 实验二



### 总结

- 利用 dd 测试文件读取速度 ` dd if=file of=/dev/null bs=1M `
- 由于缓存的存在，dd 测试文件系统的性能工具🔧，可能导致严重失真实

### 精彩评论

```
1.top 看到了%iowait升高
2.dstat 看到了wait升高时 read同步升高. 说明跟磁盘相关
3.$ perf record -g ; $ perf report 定位到了跟磁盘相关的系统调用 sys_read(). new_sync_read 和 blkdev_direct_IO 定位到了跟直接读有关系.
4.查看代码 找到了跟磁盘相关的系统调用 open.
缓存角度分析的流程是:
1.进程5秒缓存命中率100%,但是只命中了1024次,推算使用缓存4MB.实际每秒0.8MB
2.看日志知道每次读取的是32MB.[实际也可以通过dstat vmstat等工具粗略推算出该值]
3.预期的32M与实际的0.8M相差甚远. 来找原因.
4.strace 查看系统调用 定位到了openat 及 直接给出了调用参数 O_DIRECT
5.查看代码 找到了跟磁盘相关的系统调用 open.
```

关于 pcstat 工具的安装：
```
pcstat 不使用代理安装：
if [ $(uname -m) == "x86_64" ] ; then
    curl -L -o pcstat https://github.com/tobert/pcstat/raw/2014-05-02-01/pcstat.x86_64
else
    curl -L -o pcstat https://github.com/tobert/pcstat/raw/2014-05-02-01/pcstat.x86_32
fi
```

**Comment by 0XFF-96** [comment]
### 内存泄漏了，我该如何定位和处理

#### 知识点
- malloc() 申请虚拟内存，并不会立即为其分配物理内存
- CPU 与磁盘的性能差异

### 内存事故
- 没正确回收分配后的内存，导致泄漏
- 访问的是已配内存边界外的地址，导致程序异常退出

### 操作
- 通过 memleak 工具查找内存泄漏栈信息， $ /usr/share/bcc/tools/memleak -p $(pidof app) -a

**Comment by 0XFF-96** [comment]
### 为什么系统的 swap 变高了

#### 内存紧张导致的两种结果
- 内存回收
- OOM 杀死进程

### 系统如何进行内存回收？
- 内存回收指，系统释放可以回收的内存，通常指缓存和缓冲区
- 对脏页的回收，通过 系统调用 fsync 同步到磁盘 or 通过内核线程 pdflush 脏页的刷新

### 什么是 Swap ?
- 把进程暂时不用的内存数据存储到磁盘中，并释放这些数据占用的内存


### 系统什么时候需要回收内存？ 
![image](https://user-images.githubusercontent.com/19239600/84557829-cada6f00-ad60-11ea-851a-f67b1d7becc4.png)

- 页低阈值可以通过 `proc/sys/vm/min_free_kbytes` 间接设置。 

### NUMA 与 Swap 

#### 为什么内存很多，也会发生 Swap ?

- numactl --hardware
- cat /proc/zoneinfo , 通过两个信息的对比
- /proc/sys/vm/zone_reclaim_mode 来调整 NUMA 本地内存的回收策略

### 结论
- 大部分应用都不需要 swap !! （k8s, hadoop ) 

```
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html

https://dzone.com/articles/just-say-no-swapping
```

### 为什么 k8s 不开启 swap ?
- 性能问题， 开启后 swap 会严重影响性能 （内存和 IO)
- 管理问题，开启 swap 后，通过 cgroups 设置的内存上限就会失效

## 疑惑
- 什么是 numa ?

**Comment by 0XFF-96** [comment]
### 为什么系统的 Swap 变高了（下）

### 什么是文件页 & 匿名页
- https://www.cnblogs.com/linhaostudy/p/12064563.html
- 文件页、脏页、文件映射页、匿名页
- https://zhuanlan.zhihu.com/p/94784543

### Linux 内存管理
- 页面回收触发方式
- 哪些页框可以被回收
- 回收页的操作与分类
> https://www.jianshu.com/p/7ab51b8a6368

#### swap 页的调整
- `/proc/sys/vm/min_free_kbytes` 调整系统定期回收内存的阈值
- `/proc/sys/vm/swappiness` 调整文件页和匿名页的回收倾向 


#### 参考
- https://toutiao.io/posts/n4hzg1/preview

**Comment by 0XFF-96** [comment]
### 套路：如何找到系统内存的问题

#### 内存性能指标
> 已用内存、剩余内存、共享内存、可用内存、缓存和缓冲区的使用量
- 共享内存。 利用 tmpfs 实现，是一种特殊的缓存
- 内存。 剩余内存和可回收缓存
- 缓冲。 一、磁盘读取文件的页缓冲。 二、Slab 分配器中的可用回收内存
- 缓冲区。 对原始磁盘块的临时存储，用来缓冲将要写入磁盘的数据

![image](https://user-images.githubusercontent.com/19239600/84585274-ae156880-ae40-11ea-95d4-5b8c37a2ec13.png)


### 内存性能工具🔧

- free。 查看整系统的整体内存情况
- vmstat。 动态查看内存变化。 通过 proc 文件系统，找到内存指标的来源
- memleak。 确定内存泄漏时，内存所分配的栈
- sar 。 缓冲区和 swap 升高的问题
- cachetop 。 缓冲区升高的根源


### 性能指标和工具的联系🔧
![image](https://user-images.githubusercontent.com/19239600/84585333-7f4bc200-ae41-11ea-8040-20893e327c89.png)


### 根据工具🔧查指标（内存性能） 

![image](https://user-images.githubusercontent.com/19239600/84585336-8ecb0b00-ae41-11ea-8e6a-e190e15c0ab1.png)


### 问题分析思路

![image](https://user-images.githubusercontent.com/19239600/84586050-6266bd00-ae48-11ea-855a-a784e9c481f8.png)


### 小结

- 禁用 swap。 降低 swappiness 的值，减少内存回收时 swap 的使用倾向 
- 减少内存的动态分配。 内存池、大页（huge page） 
- 尽量使用缓存和缓存区来访问数据
- 使用 cgroups 等方式限制进程的内存使用情况
- 通过`/proc/pid/oom_adj` 调整核心应用的 oom_score

**Comment by 0XFF-96** [comment]
### 文件系统与磁盘的区别（答疑）

#### 内存回收与 OOM 
- 怎么理解 LRU 内存回收 ？
- 回收后的内存又到哪里去了？
- OOM 是按照虚拟内存还是实际内存来打分？
OOM 触发的时机，基于虚拟内存。进程在申请内存时，如果申请的虚拟内存加上服务器实际已用的内存之和，比总的物理内存还大，就会触发 OOM 。 

- 怎么估计应用的最小内存？

### /proc/meminfo 指标
- cat /proc/meminfo | grep -i active | sort 


### 文件系统与磁盘的区别
![image](https://user-images.githubusercontent.com/19239600/84586290-defa9b00-ae4a-11ea-9cdf-35a54785b32a.png)
- cache 是针对文件系统的缓存， buffers 是对磁盘数据的缓存

###  如何统计所有进程的物理内存使用量？
- RSS 表示常驻内存，把进程的共享内存也算进去，会导致重复计算问题。 
- PSS 的含义是什么？
- 文件系统的文档： https://www.kernel.org/doc/Documentation/filesystems/proc.txt

- https://unix.stackexchange.com/questions/33381/getting-information-about-a-process-memory-usage-from-proc-pid-smaps
Getting information about a process' memory usage from /proc/pid/smaps
```

# 使用grep查找Pss指标后，再用awk计算累加值
$ grep Pss /proc/[1-9]*/smaps | awk '{total+=$2}; END {printf "%d kB\n", total }'
391266 kB
```
### 内存泄漏案例的优化方法
